# Services
services:

  # Testimony Service
  testimony-app:
    container_name: testimony-app
    image: opeoniye/nginx-php-fpm
    environment:
      GIT_REPO: ${GIT_REPO}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_NAME: ${GIT_NAME}
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
      WEBROOT: ${WEBROOT}
    ports:
      - 1001:80
    networks:
      - testimony
    # volumes:
    #   - ./.docker/nginx/testify.conf:/etc/nginx/sites-available/default.conf
      #- ./.env:/var/www/html
    restart: always

networks:
  testimony:
    name: testimony