# Services
services:

  # DDC Service
  ddc-app:
    container_name: ddc-app
    image: richarvey/nginx-php-fpm
    environment:
      GIT_REPO: ${GIT_REPO}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_NAME: ${GIT_NAME}
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
      WEBROOT: ${WEBROOT}
    ports:
      - 1000:80
    networks:
      - ddc
    #volumes:
      #- .:/var/www
      #- ./.env:/var/www/html
    restart: always

networks:
  ddc:
    name: ddc