# Services
services:

  # Testimony Service
  testimony-app:
    container_name: testimony-app
    image: opeoniye/nginx-php-fpm:2.1.2
    environment:
      RUN_SCRIPTS: ${RUN_SCRIPTS}
      PUID: ${PUID}
      PGID: ${PGID}
    ports:
      - 1004:80
      - 4004:443
    networks:
      - dclm-testimony
    volumes:
      - .:/var/www/html
      - ../ops/docker/nginx/testify-prod.conf:/etc/nginx/sites-available/default.conf
      - ../ops/docker/nginx/proxy:/etc/nginx/proxy_params
      - ../ops/docker/nginx/ssl.conf:/etc/nginx/ssl.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

networks:
  dclm-testimony:
    name: testimony