# Services
services:

  # Testimony Service
  testimony-app:
    container_name: testimony-app
    image: richarvey/nginx-php-fpm:latest
    environment:
      RUN_SCRIPTS: ${RUN_SCRIPTS}
    ports:
      - 1001:80
      - 4443:443
    networks:
      - bams
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/testify-dev.conf:/etc/nginx/sites-available/default.conf
      - ./.docker/nginx/proxy:/etc/nginx/proxy_params
      - ./.docker/nginx/ssl.conf:/etc/nginx/ssl.conf
      - ~/dev/keys/mac:/var/keys/mac
    restart: always

networks:
  bams:
    name: bams-dev
    external: true 