# Services
services:

  # Testimony Service
  testimony-app:
    container_name: testimony-app
    image: docker.io/bitnami/laravel:8
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - 1001:8000
      - 4001:443
    networks:
      - dclm
    volumes:
      - .:/app
    restart: always

networks:
  dclm:
    name: dclm
    external: true