# Services
services:

  # Testimony Service
  testimony-app:
    container_name: testimony-app
    image: richarvey/nginx-php-fpm:latest
    # environment:
      # GIT_REPO: ${GIT_REPO}
      # GIT_EMAIL: ${GIT_EMAIL}
      # GIT_NAME: ${GIT_NAME}
      # GIT_BRANCH: ${GIT_BRANCH}
      # GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
      # WEBROOT: ${WEBROOT}
    ports:
      - 1004:80
    networks:
      - dclm-testimony
    volumes:
      - ./:/var/www/html
      - ./.docker/testify.conf:/etc/nginx/sites-available/default.conf
      # - ./.env:/var/www/html/.env
    restart: always

networks:
  dclm-testimony:
    name: testimony